config/routes.rb
ChemicalInventory::Application.routes.draw do
  resources :chemicals
  
  resources :imports
  match 'upload_chemfile' => 'imports#new'

  root :to => 'chemicals#index'

end

app/models/chemical.rb
class Chemical < ActiveRecord::Base
  has_attached_file :msds
  
  before_save :capitalize_name
  
  def capitalize_name
    self.name.capitalize!
  end
end

app/models/import.rb
class Import < ActiveRecord::Base
  require "csv"
  
  has_attached_file :chemfile
  
  def extract_chemicals_from_chemfile
    
     CSV.foreach(self.chemfile.to_file.path, {:headers => true, :return_headers => true}) do |row|
        
        @chemical = Chemical.create(
          :name => row.field("name"),
          :amount => row.field("amount"),
          :quantity => row.field("quantity"),
          :location => row.field("location"),
          :storage => row.field("storage"),
          :notes => row.field("storage"),
          :formula => row.field("formula"),
          :cas => row.field("cas"),
          :supplier => row.field("supplier"),
          :catalognumber => row.field("catalognumber"),
          :smiles => row.field("smiles"),
          :inchi => row.field("inchi")
        )
        
     end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/chemicals_controller.rb
class ChemicalsController < ApplicationController
  require 'csv'
  # GET /chemicals
  # GET /chemicals.json
  def index
    #@chemicals = Chemical.all
    @chemicals = Chemical.order("name ASC").page params[:page]
    
    # session[:ChemicalInventory_current_page] = params[:page] ? params[:page] : 1
    cookies[:chemical_inventory_current_page] = params[:page] ? params[:page] : 1
    
    respond_to do |format|
      format.html
      format.json { render json: @chemicals }
      format.csv {
            chemicals = Chemical.order("name ASC")
            csv = CSV.generate do |csv|
              csv << ["Name", "CAS", "IUPAC Formula","SMILES", "InChI", "AMT", "QTY", "Location", "Storage", "Notes", "Supplier", "Catalog Number", "Date Entered"]
              chemicals.each do |item|
                csv << [item.name, item.cas, item.formula, item.smiles, item.inchi, item.amount, item.quantity, item.location, item.storage, item.notes, item.supplier, item.catalognumber, item.created_at]
              end
            end

            send_data(csv, :filename => 'chemicals.csv', 
                      :type => 'text/csv', :disposition => 'attachment')
          }
    end
  end

  # GET /chemicals/1
  # GET /chemicals/1.json
  def show
    @chemical = Chemical.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @chemical }
    end
  end

  # GET /chemicals/new
  # GET /chemicals/new.json
  def new
    @chemical = Chemical.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @chemical }
    end
  end

  # GET /chemicals/1/edit
  def edit
    @chemical = Chemical.find(params[:id])
  end

  # POST /chemicals
  # POST /chemicals.json
  def create
    @chemical = Chemical.new(params[:chemical])

    respond_to do |format|
      if @chemical.save
        format.html { redirect_to @chemical, notice: 'Chemical was successfully created.' }
        format.json { render json: @chemical, status: :created, location: @chemical }
      else
        format.html { render action: "new" }
        format.json { render json: @chemical.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /chemicals/1
  # PUT /chemicals/1.json
  def update
    @chemical = Chemical.find(params[:id])

    respond_to do |format|
      if @chemical.update_attributes(params[:chemical])
        format.html { redirect_to @chemical, notice: 'Chemical was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @chemical.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chemicals/1
  # DELETE /chemicals/1.json
  def destroy
    @chemical = Chemical.find(params[:id])
    @chemical.destroy

    respond_to do |format|
      format.html { redirect_to chemicals_url }
      format.json { head :ok }
    end
  end
end

app/controllers/imports_controller.rb
class ImportsController < ApplicationController

  
  def new
    @import = Import.new

     respond_to do |format|
       format.html # new.html.erb
     end
     
  end
  
  def create
    @import = Import.new(params[:import])
    respond_to do |format|
      if @import.save
        format.html { redirect_to(chemicals_path)}
        flash[:notice] = "File Uploaded."
        @import.extract_chemicals_from_chemfile
        flash.now[:notice] = "Chemicals Added."
      else
        format.html { render :action => "new" }
      end
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chemicals_helper.rb
module ChemicalsHelper
  def number_of_chemicals
    chemical_count = Chemical.all.size
  end
  def has_msds(arg)
    my_arg = arg
    if my_arg.msds.original_filename.nil?
      #bw image
      render :inline => "<%= image_tag('msds_bw.png') %>"
    else
      #color image
      #<%= link_to image_tag("search.gif", :border=>0), :action => 'show', :id => user %>
      render :partial => 'msdsimage', :locals => { :chemical => my_arg }
    end
  end
end

app/helpers/imports_helper.rb
module ImportsHelper
end

app/views/chemicals/_form.html.erb
<%= form_for @chemical, :html => { :multipart => true } do |f| %>
  <% if @chemical.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chemical.errors.count, "error") %> prohibited this chemical from being saved:</h2>

      <ul>
      <% @chemical.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
    <p>
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </p>
  	<p>
  		<%= f.label :cas %><br />
  		<%= f.text_field :cas %>
  	</p>
  	<p>
  		<%= f.label :formula %><br />
  		<%= f.text_field :formula %>
  	</p>
  	<p>
  		<%= f.label :amount %><br />
  		<%= f.text_field :amount %>
  	</p>
  	<p>
  		<%= f.label :quantity %><br />
  		<%= f.text_field :quantity %>
  	</p>
  	<p>
  		<%= f.label :location %><br />
  		<%= f.text_field :location %>
  	</p>
  	<p>
  		<%= f.label :storage %><br />
  		<%= f.text_field :storage %>
  	</p>
  	<p>
  		<%= f.label :smiles %><br />
  		<%= f.text_field :smiles %>
  	</p>
  	<p>
  		<%= f.label :inchi %><br />
  		<%= f.text_field :inchi %>
  	</p>
  	<p>
  		<%= f.label :supplier %><br />
  		<%= f.text_field :supplier %>
  	</p>
  	<p>
  		<%= f.label :catalognumber %><br />
  		<%= f.text_field :catalognumber %>
  	</p>
  	<p>
  		<%= f.label :notes %><br />
  		<%= f.text_area :notes %>
  	</p>
  	<p>
  		<%= f.label :msds %><br />
  		<%= f.file_field :msds %>
  	</p>

  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chemicals/_msdsimage.html.erb
<%= link_to(image_tag("msds.png", :border => 0), chemical.msds.url) %>

app/views/chemicals/edit.html.erb
<h1>Editing chemical</h1>

<%= render 'form' %>

<%= link_to 'Show', @chemical %> |
<%= link_to 'Back', chemicals_path %>

app/views/chemicals/index.html.erb
<% content_for(:title, "Chemicals") %>
<h2>Currently Storing <%= number_of_chemicals %> Chemicals</h2>

<div id="controls">
	Functions:
	<%= link_to 'Add a New Chemical', new_chemical_path %> |
	<%= link_to 'Export Database', chemicals_path(:csv) %> |
	<%= link_to 'Upload Chemfile', new_import_path %>
</div>
<%= paginate @chemicals %>
<div id="chemtable">
	<table>
	  <tr>
	    <th>Name</th>
			<th>CAS</th>
			<th>Formula</th>
	    <th>AMT.</th>
	    <th>QTY.</th>
			<th>Location</th>
			<th>Storage</th>
			<th>Notes</th>
			<th>Date Entered</th>
			<th>MSDS</th>
			<th colspan="2">Actions</th>
	  </tr>
	  <% for chemical in @chemicals %>
	    <tr class=<%= cycle('odd', 'even') %>>
	      <td><%= link_to(h(chemical.name), chemical) %><br /> <span class="infolinks">{ <%= link_to "PubChem", "http://www.ncbi.nlm.nih.gov/sites/entrez?db=pcsubstance&cmd=search&term=#{chemical.name}", :popup => TRUE, :class => "pubchemlinks" %> | <%= link_to "NIST", "http://webbook.nist.gov/cgi/cbook.cgi?Name=#{chemical.name}&Units=SI", :popup => TRUE, :class => 'nistlink'  %> }</span></td>
				<td><%=h chemical.cas %></td>
				<td><%=h chemical.formula %></td>
				<td><%=h chemical.amount  %></td>
				<td><%= h chemical.quantity %></td>
				<td><%= h chemical.location %></td>
				<td><%= h chemical.storage %></td>
				<td><% if chemical.notes? %>Read More<% end %></td>
				<td><%= h chemical.created_at.to_s(:month_and_year) %></td>
				<td class="msds"><%= has_msds(chemical) %></td>
	      <td class="actions"><%= link_to "Edit", edit_chemical_path(chemical) %></td>
	      <td class="actions"><%= link_to "Destroy", chemical, :confirm => 'Are you sure?', :method => :delete %></td>
	    </tr>
	  <% end %>
	</table>
</div>

<%= paginate @chemicals %>

app/views/chemicals/new.html.erb
<h1>New chemical</h1>

<%= render 'form' %>

<%= link_to 'Back', chemicals_path %>

app/views/chemicals/show.html.erb
<h1><%=h @chemical.name %></h1>

<p>
  <strong>Name:</strong>
  <%=h @chemical.name %>
</p>
<p>
  <b>Amount:</b>
  <%= @chemical.amount %>
</p>
<p>
  <b>Quantity:</b>
  <%= @chemical.quantity %>
</p>
<p>
  <b>Location:</b>
  <%= @chemical.location %>
</p>
<p>
  <b>Storage:</b>
  <%= @chemical.storage %>
</p>
<p>
  <b>Notes:</b>
  <%= @chemical.notes %>
</p>
<p>
  <b>Formula:</b>
  <%= @chemical.formula %>
</p>
<p>
  <b>CAS:</b>
  <%= @chemical.cas %>
</p>
<p>
  <b>Supplier:</b>
  <%= @chemical.supplier %>
</p>
<p>
  <b>Catalog Number:</b>
  <%= @chemical.catalognumber %>
</p>
<p>
  <b>SMILES:</b>
  <%= @chemical.smiles %>
</p>
<p>
  <b>INCHI:</b>
  <%= @chemical.inchi %>
</p>




<%= link_to 'Edit', edit_chemical_path(@chemical) %> |
<%= link_to 'Back', chemicals_path(:page => cookies[:chemical_inventory_current_page]) %>

app/views/imports/_form.html.erb
<%= form_for @import, :html => { :multipart => true } do |f| %>
  <p>
		<%= f.label :chemfile %><br />
		<%= f.file_field :chemfile %>
	</p>
	<div class="actions">
    <%= f.submit %>
  </div>
<% end %>  

app/views/imports/new.html.erb
<h1>Upload Chemfile</h1>

<%= render 'form' %>

<%= link_to 'Back', chemicals_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= h(yield(:title) || "Chemical Inventory") %></title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class="chemicals">
  
<div id="container">
  <% if flash[:notice] %>
        <p class="notice"><%= flash[:notice] %></p>
  <% end %>
  <% if flash[:error] %>
        <p class="error"><%= flash[:error] %></p>
  <% end %>
  
  <%= yield %>
</div>

</body>
</html>